version: '2'
services:
  mongodb:
    image: "mongo"
    ports:
     - "6300:6300"
  api:
    build: ./api/
    environment:
      PORT: "6200"
    ports:
      - "6200:6200"
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - mongodb
