version: 2
jobs:
  TSApi:
    working_directory: ~/repo

    docker:
      - image: circleci/node:10
      - image: mongo:3.6

    environment:
      environment: 'test'
      COVERALLS_REPO_TOKEN: 'wHig9mDejonNwbBoAU7C3lD1Tpf51X7Nb'

    steps:
      - checkout

      - restore_cache:
          keys:
            - TSApi-{{ .Branch }}-{{ checksum "TSApi/package.json" }}
            - TSApi-{{ .Branch }}
            - TSApi-production-{{ checksum "TSApi/package.json" }}
            - TSApi-production

      - run:
          name: Install dependencies
          command: cd TSApi && npm install

      - save_cache:
          key: TSApi-{{ .Branch }}-{{ checksum "TSApi/package.json" }}
          paths:
            - TSApi/node_modules

      - run:
          name: Run tests
          command: cd TSApi && npm run test -- -- --coverage -w=2

      - run:
          name: Send coverage report
          command: cd TSApi && npm run sendCoverageReport

      - run:
          name: Clean coverage report
          command: cd TSApi && rm -rf coverage

workflows:
  version: 2
  stack:
    jobs:
      - TSApi
